### ISSUE TITLE
MockK framework is using dexmaker

### ISSUE THREAD

**Issue by oleksiyp** [linkedin/dexmaker#103]
Hi,

I took dexmaker-inline-mockito and dexmaker-inline-static-mockito as a base and built a solution for [MockK](http://mockk.io/) mocking framework. This is Kotlin framework, which is quite popular and competing with Mockito wrapper for Kotlin. 

Here is sources [dex maker branch](https://github.com/oleksiyp/mockk/tree/dexmaker/agent/android) and [PR](https://github.com/oleksiyp/mockk/pull/68)

I have a set of ~300 tests running for Java, so I adpoted around 260 of them to run on dexmaker based version. I fixed few issues. Alike mocking of Exception and HashMap.

What I can admit:

- Tests are running pretty slow (going to spend some time for optimization)
- Not sure I understand how convenient for users limitation to Android P
- I don't know what should I do with License terms and copyrights (should I just keep them?)
- I don't know yet how to integrate it to continuous integration build (running emulator probably, but not yet touched that)
- I would need to follow-up all the changes to dexmaker since current commit to keep my project in sync.

Would appreciate any answers from your experience.

Thanks!

**Comment by moltmann** [comment]
Open source at work.

When using byte code transformation via JVMTI the most significant performance hit is the first memory access to the `class_data` parameter of the ClassFileLoadHook. This is when the standard compliant dex file will get generated and I saw this taking up to seconds. If you ever can, you want to avoid this. In dexmaker-mockito-inline-extended this is used in two cases. (1) when adding the method entry hooks for [instance](https://github.com/linkedin/dexmaker/blob/master/dexmaker-mockito-inline/src/main/jni/dexmakerjvmtiagent/agent.cc#L88) and [static](https://github.com/linkedin/dexmaker/blob/master/dexmaker-mockito-inline-extended/src/main/jni/staticjvmtiagent/agent.cc#L88) methods. This is only ran one per class + once again for the static methods of the class. (2) When calling a static method it might not be clear what class the method was called on. Hence we have to [look at the calling byte code](https://github.com/linkedin/dexmaker/blob/master/dexmaker-mockito-inline-extended/src/main/java/com/android/dx/mockito/inline/StaticMockMethodAdvice.java#L160) to figure that out. That can make calling static methods very, very expensive.

There were some issues with JVMTI that were fixed in P, hence this code only works with P. You might be able to transform app and test classes during first load in the class loader or on the host before packaging them into the apk. Android classes are already loaded before the process is created, hence for these you want JVMTI.

I _assume_ copying code and changing the copyright is not ok. I am not a lawyer, please consult one.

I think Travis allows you to run tests in you CI system from github.

If you copy code, you need to keep copying. Much better is to just pull in the lib as a whole. Not sure if this would work for you.

**Comment by oleksiyp** [comment]
Thanks for answers.

Looks like I need to check copyright stuff myself, as Apache license allow copy, change and usage, only dont allow producing software named same way. i.e. you shouldnt copy "tomcat", change it, build it and distribute it under same name "tomcat", all the rest is OK. Anyway will doublecheck it

I changed a lot of code, but in general it looks same. I kept copyrights, but totally not sure its right thing, because this changed code were not submitted for copyrighting under stated copyright and apache license allow to derive things. Will check

Looks like I merged static and regural method transformations too fast. There was a lot of code duplication. Now it makes static class tranform for each class transformed for regular mock. So need two-stage transform to speed up, firstly it would tranform for regular mocks and only if demanded retranforms to static+regular.

Building in most of CIs is not possible. Only x86 image for Android P is available and travis(circle) CI is not able to run x86 VM in VM. (Arm is working but very slow, no Android P image for arm anyway). So be aware of it. This seems very limmiting for end-user. Thus I am going to implement fallback solution via subclassing
