### ISSUE TITLE
Migrate away from JCenter

### ISSUE THREAD

**Issue by steffandroid** [linkedin/dexmaker#172]
[JFrog](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) has just announced that it will be shutting down JCenter on May 1st. JCenter is the sole repository hosting this library, so it will become unavailable after this date unless migrated to an alternative service.

**Comment by drewhannay** [comment]
Thanks for the ticket. We've started looking at this for all of our Android open source projects, we'll make sure it happens!

**Comment by steffandroid** [comment]
Awesome! Thanks for the confirmation.

**Comment by gildor** [comment]
@drewhannay any updates on this?

**Comment by drewhannay** [comment]
Ah, apologies, this has happened already! I had a nagging feeling I was forgetting about an issue someone had opened 😄 

Check out [Release 2.28.1](https://github.com/linkedin/dexmaker/releases/tag/2.28.1), it should be available on Maven Central.

**Comment by gildor** [comment]
Thanks!
Do you plan to re-upload older versions of dexmaker? just in case, dependency which I use depends on dexmaker-2.21, I will create an issue to update to the newer dexmaker, but it also means that when JCenter will be shutdown completely, all older versions of dexmaker will not be avilable

JCenter has an option to sync all dependencies with Maven Central, but it will shutdown UI very soon, so it will not be possible

**Comment by drewhannay** [comment]
I haven't looked into it much to be honest, but from what I understand, re-uploading would be a little tough since we didn't sign any of the older artifacts with a GPG key and some of them may not have had the source or javadoc jars needed to pass Maven Central validation. The good news is your downstream dependencies have until Feb 2022 before consuming artifacts from JCenter shuts down, so hopefully they'll be able to upgrade by then?
