### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by warabei14** [linkedin/dexmaker#78]
Hi. The last one has been pushed over the year ago. Some nice fixes have been done up to this time. Any chance to have some release in near time?

**Comment by drewhannay** [comment]
Version [2.12.1](https://github.com/linkedin/dexmaker/blob/master/CHANGELOG.md#version-2121-2018-01-15) has been published now. I accidentally missed the latest commit when publishing 2.12.0, which is why there's a 2.12.1 that has everything.

Note that the new dexmaker-inline artifacts are **not** published and won't be available until Android P is released.
